stages:
  - build
  - test

maven_build:
  image: maven:3.6.3-jdk-11
  stage: build
  script:
    - mvn package -B
  artifacts:
    paths:
      - target/*.jar

test:
  image: maven:3.6.3-jdk-11
  stage: test
  script:
    - mvn -X test
