stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository

build:
  image: maven:3.6.3-jdk-11
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

test:
  image: maven:3.6.3-jdk-11
  stage: test
  script:
    - mvn test

heroku_deploy:
  image: docker:stable
  stage: deploy
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login --username=$HEROKU_USER --password=$HEROKU_API_KEY registry.heroku.com
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build --build-arg JAR_FILE=`ls target/*.jar | head -1` --env DATASOURCE_URL=$SPRING_DATASOURCE_URL --env DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME --env DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD  --tag registry.heroku.com/$HEROKU_APP_NAME/web .
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web
    - ./release-app-in-heroku.sh $HEROKU_APP_NAME $HEROKU_API_KEY

