version: 2.1

orbs:
  maven: circleci/maven@1.0.0

jobs:
  build:
    working_directory: ~/timeforpizzabackend
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps:

      - checkout

      - run: mvn clean install

      - store_artifacts:
          path: target/timeforpizzabackend-0.0.5-SNAPSHOT.jar

  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: mvn -X test



workflows:
  build-and-test:
    jobs:
      - build
      - test:
        requires:
          - build